# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\mapdialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mapDialog(object):
    def setupUi(self, mapDialog):
        mapDialog.setObjectName("mapDialog")
        mapDialog.resize(259, 160)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(mapDialog.sizePolicy().hasHeightForWidth())
        mapDialog.setSizePolicy(sizePolicy)
        mapDialog.setMinimumSize(QtCore.QSize(0, 160))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        mapDialog.setFont(font)
        self.verticalLayout = QtWidgets.QVBoxLayout(mapDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.hlP1 = QtWidgets.QHBoxLayout()
        self.hlP1.setObjectName("hlP1")
        self.lblP1 = QtWidgets.QLabel(mapDialog)
        self.lblP1.setObjectName("lblP1")
        self.hlP1.addWidget(self.lblP1)
        self.leP1FileLocation = QtWidgets.QLineEdit(mapDialog)
        self.leP1FileLocation.setReadOnly(True)
        self.leP1FileLocation.setObjectName("leP1FileLocation")
        self.hlP1.addWidget(self.leP1FileLocation)
        self.btnP1LoadFile = QtWidgets.QPushButton(mapDialog)
        self.btnP1LoadFile.setMinimumSize(QtCore.QSize(0, 20))
        self.btnP1LoadFile.setObjectName("btnP1LoadFile")
        self.hlP1.addWidget(self.btnP1LoadFile)
        self.verticalLayout.addLayout(self.hlP1)
        self.hlP2 = QtWidgets.QHBoxLayout()
        self.hlP2.setObjectName("hlP2")
        self.lblP2 = QtWidgets.QLabel(mapDialog)
        self.lblP2.setObjectName("lblP2")
        self.hlP2.addWidget(self.lblP2)
        self.leP2FileLocation = QtWidgets.QLineEdit(mapDialog)
        self.leP2FileLocation.setReadOnly(True)
        self.leP2FileLocation.setObjectName("leP2FileLocation")
        self.hlP2.addWidget(self.leP2FileLocation)
        self.btnP2LoadFile = QtWidgets.QPushButton(mapDialog)
        self.btnP2LoadFile.setMinimumSize(QtCore.QSize(0, 20))
        self.btnP2LoadFile.setObjectName("btnP2LoadFile")
        self.hlP2.addWidget(self.btnP2LoadFile)
        self.verticalLayout.addLayout(self.hlP2)
        self.hlBtn = QtWidgets.QHBoxLayout()
        self.hlBtn.setObjectName("hlBtn")
        self.btnLoadExpl = QtWidgets.QPushButton(mapDialog)
        self.btnLoadExpl.setMinimumSize(QtCore.QSize(0, 20))
        self.btnLoadExpl.setObjectName("btnLoadExpl")
        self.hlBtn.addWidget(self.btnLoadExpl)
        self.btnLoadFastPath = QtWidgets.QPushButton(mapDialog)
        self.btnLoadFastPath.setMinimumSize(QtCore.QSize(0, 20))
        self.btnLoadFastPath.setObjectName("btnLoadFastPath")
        self.hlBtn.addWidget(self.btnLoadFastPath)
        self.verticalLayout.addLayout(self.hlBtn)

        self.retranslateUi(mapDialog)
        QtCore.QMetaObject.connectSlotsByName(mapDialog)

    def retranslateUi(self, mapDialog):
        _translate = QtCore.QCoreApplication.translate
        mapDialog.setWindowTitle(_translate("mapDialog", "Map Dialog"))
        self.lblP1.setText(_translate("mapDialog", "P1:"))
        self.leP1FileLocation.setPlaceholderText(_translate("mapDialog", "File Location"))
        self.btnP1LoadFile.setText(_translate("mapDialog", "Load File"))
        self.lblP2.setText(_translate("mapDialog", "P2:"))
        self.leP2FileLocation.setPlaceholderText(_translate("mapDialog", "File Location"))
        self.btnP2LoadFile.setText(_translate("mapDialog", "Load File"))
        self.btnLoadExpl.setText(_translate("mapDialog", "Load map for exploration"))
        self.btnLoadFastPath.setText(_translate("mapDialog", "Load map for Fastest Path"))
